language: java

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
  
jdk:
- openjdk11

install: true
    
addons:
  sonarcloud:
    organization: "qses" 
    token: $SONAR_TOKEN
      
script:
  - mvn compile sonar:sonar -Dsonar.projectKey=qses_WebGoat
  
